### ISSUE TITLE
Support for Goose?

### ISSUE THREAD

**Issue by justyns** [Dhravya/install-mcp#4]
Any interest in adding support for [Goose](https://block.github.io/goose/) as a client?.

Goose stores mcp server settings in `~/.config/goose/config.yaml` by default and looks like this:

```yaml
extensions:
  fetch:
    name: GitHub
    cmd: npx
    args: [-y @modelcontextprotocol/server-github]
    enabled: true
    envs: { "GITHUB_PERSONAL_ACCESS_TOKEN": "<YOUR_TOKEN>" }
    type: stdio
    timeout: 300
```

Example from https://block.github.io/goose/docs/getting-started/using-extensions#config-entry

More info on the config file: https://block.github.io/goose/docs/guides/config-file
